### ISSUE TITLE
[Feat] 아카이브 페이지 데이터 적용

### ISSUE THREAD

**Issue by bravej1x4** [DeveloperAcademy-POSTECH/MC2-Team13-Ddojeon#21]
---
# Description

 - 아카이브 페이지 데이터 적용 작업

---

# Tasks
- [x] 코어 데이터 연동
- [x] 세부 페이지 데이터 연동

 # ETC
...

**Comment by JJunghyunY** [comment]
메인 브랜치 머지 완료
