### ISSUE TITLE
런치스크린 만들기

### ISSUE THREAD

**Issue by SeBin-Kwon** [DeveloperAcademy-POSTECH/MC2-Team13-Ddojeon#59]
---
# Description

 - 런치스크린 제작

---

# Tasks
- [ ] Task 1
- [ ] Task 2

 # ETC
...

**Comment by JJunghyunY** [comment]
런치스크린 적용 완료~

**Comment by JJunghyunY** [comment]
올링이 제작한 asset으로 launch screen 적용 완료!
